name: Security Scan

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * 1'  # Каждый понедельник в 2:00

jobs:
  security:
    name: Security Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bandit safety

      - name: Run Bandit security scan
        run: |
          bandit -r . -f json -o bandit-report.json || true
          bandit -r . -f txt -o bandit-report.txt || true

      - name: Run Safety check
        run: |
          safety check --json --output safety-report.json || true
          safety check --text --output safety-report.txt || true

      - name: Upload security reports
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: |
            bandit-report.json
            bandit-report.txt
            safety-report.json
            safety-report.txt
          retention-days: 30

      - name: Comment PR with security findings
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v8
        with:
          script: |
            const fs = require('fs');
            
            let banditOutput = '';
            let safetyOutput = '';
            
            try {
              if (fs.existsSync('bandit-report.txt')) {
                banditOutput = fs.readFileSync('bandit-report.txt', 'utf8');
              }
            } catch (e) {
              console.log('No bandit report found');
            }
            
            try {
              if (fs.existsSync('safety-report.txt')) {
                safetyOutput = fs.readFileSync('safety-report.txt', 'utf8');
              }
            } catch (e) {
              console.log('No safety report found');
            }
            
            const comment = `## 🔒 Security Scan Results
            
            ### Bandit Security Analysis
            \`\`\`
            ${banditOutput || 'No security issues found'}
            \`\`\`
            
            ### Safety Dependency Check
            \`\`\`
            ${safetyOutput || 'No vulnerable dependencies found'}
            \`\`\`
            
            ---
            *This report was generated automatically by GitHub Actions*`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });
